### ISSUE TITLE
Error in using logs within queued Jobs

### ISSUE THREAD

**Issue by gorankrgovic** [pagevamp/laravel-cloudwatch-logs#7] opened 2019-01-04 21:04 UTC
In Laravel 5.7.19 (latest) this driver is not working at all within the Job class nor within the queued Listeners. Tried also with using

```php
Log::channel(...)
```
and without channel. (ie Log::info...)

Error message from the default laravel.log file is:

```
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ErrorException(code: 0): Undefined index: driver at /some/path/Sites/demo/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:170)
```

**Comment by developernaren** [comment] 2019-02-11 11:50
@gorankrgovic hey sorry for late reply. I was really busy with things. I do not see changes in laravel itself that would break this. https://github.com/laravel/laravel/compare/v5.7.15...v5.7.19 

Is there anything specific to your environment and what is the last version of Laravel this package worked with, for you?

**Comment by developernaren** [comment] 2019-02-11 11:58
Hey sorry for late reply. I was really busy with personal things.
There does not seem to be any change with Log except an addition of papertrail.
https://github.com/laravel/laravel/compare/v5.7.15...v5.7.19
There seem to be a slight change with the default. This might mean that there are permission issue with log file and system is not creating the file. Since we do not replace the file based log, it might be unable to create the file.

In any case, I need a bit more information on this.
* What was the last laravel version this worked for you?
* Are there any specific environment changes you made for this change?

**Comment by johnboc** [comment] 2019-02-12 09:45
I have just installed this package and I am getting the same error. I am using Laravel 5.7.25

**Comment by developernaren** [comment] 2019-02-12 10:33
@johnboc Please check if

* laravel.log file is writable
* if the log is set to daily, the logger can create and write daily files
* settings in the logging.php is correctly set

This is not working at all for you or just the the queues?

**Comment by johnboc** [comment] 2019-02-12 10:51
laravel.log is writable
when set to daily the logger creates files as expected
logging.php is:

```<?php

use \App\Providers\LogService;
use Monolog\Handler\StreamHandler;
use Monolog\Handler\SyslogUdpHandler;

return [
    'default' => env('LOG_CHANNEL', 'daily'),

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily'],
        ],
        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
        ],
        'daily' => [
            'driver' => 'daily',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
            'days' => 14,
        ],
        'slack' => [
            'driver' => 'slack',
            'url' => env('LOG_SLACK_WEBHOOK_URL'),
            'username' => 'Laravel Log',
            'emoji' => ':boom:',
            'level' => 'critical',
        ],
        'papertrail' => [
            'driver'  => 'monolog',
            'level' => 'debug',
            'handler' => SyslogUdpHandler::class,
            'handler_with' => [
                'host' => env('PAPERTRAIL_URL'),
                'port' => env('PAPERTRAIL_PORT'),
            ],
        ],
        'stderr' => [
            'driver' => 'monolog',
            'handler' => StreamHandler::class,
            'formatter' => env('LOG_STDERR_FORMATTER'),
            'with' => [
                'stream' => 'php://stderr',
            ],
        ],
        'syslog' => [
            'driver' => 'syslog',
            'level' => 'debug',
        ],
        'errorlog' => [
            'driver' => 'errorlog',
            'level' => 'debug',
        ],
        'cloudwatch' => [
            'name' => 'TSC',,
            'region' => 'eu-west-1'),
            'credentials' => [
                'key' => env('CLOUDWATCH_LOG_KEY', ''),
                'secret' => env('CLOUDWATCH_LOG_SECRET', '')
            ],
            'stream_name' => 'tsc1app',
            'retention' => 14,
            'group_name' => 'TSC',
            'version' => 'latest',
            'formatter' => \Monolog\Formatter\JsonFormatter::class
        ],
    ],
];
```
I am not using queues

**Comment by developernaren** [comment] 2019-02-14 04:34
@johnboc 
I tested with fresh installation and everything works fine for me. I do not get the mentioned error. Do you have any additional information that can help me debug?

Did you actually copy this config file from your project because there are few syntax errors in the file?
Can those be the issues?
```
'cloudwatch' => [
            'name' => 'TSC',
            'region' => 'eu-west-1',
            'credentials' => [
                'key' => env('CLOUDWATCH_LOG_KEY', ''),
                'secret' => env('CLOUDWATCH_LOG_SECRET', '')
            ],
            'stream_name' => 'tsc1app',
            'retention' => 14,
            'group_name' => 'TSC',
            'version' => 'latest',
            'formatter' => \Monolog\Formatter\JsonFormatter::class
        ],
```
it should instead look like this.

**Comment by gorankrgovic** [comment] 2019-02-14 08:52
Hi @developernaren, 

In my case (latest Laravel version) - Maybe I didn't describe the issue properly. Logs are working just fine if you are using them within methods or any other way other than using it within the queued Listener or a dispatched Job - then it fails for the reasons I don't have a clue why (with the message I've posted above )

**Comment by johnboc** [comment] 2019-02-14 11:30
Ok I've created a fresh project like so:
```
composer create-project --prefer-dist laravel/laravel pagevamp
cd pagevamp
composer require pagevamp/laravel-cloudwatch-logs
Using version ^0.0.5 for pagevamp/laravel-cloudwatch-logs
```
I've added the following to my config/app.php
```
'cloudwatch' => [
            'name' => 'TSC',
            'region' => 'eu-west-1',
            'credentials' => [
                'key' => env('CLOUDWATCH_LOG_KEY', ''),
                'secret' => env('CLOUDWATCH_LOG_SECRET', '')
            ],
            'stream_name' => 'tsc1app',
            'retention' => 14,
            'group_name' => 'TSC',
            'version' => 'latest',
            'formatter' => \Monolog\Formatter\JsonFormatter::class
        ],
```
In my .env file 
LOG_CHANNEL=cloudwatch
and the CLOUDWATCH_LOG_KEY and CLOUDWATCH_LOG_SECRET .env values are for a user with CloudWatchLogsFullAccess permissions

Unfortunately I am still getting the same error:
```
[2019-02-14 11:24:45] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ErrorException(code: 0): Undefined index: driver at D:\\Projects\\pagevamp\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php:171)
[stacktrace]
#0 D:\\Projects\\pagevamp\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(171): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'D:\\\\Projects\\\\pag...', 171, Array)
#1 D:\\Projects\\pagevamp\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(102): Illuminate\\Log\\LogManager->resolve('cloudwatch')
#2 D:\\Projects\\pagevamp\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(90): Illuminate\\Log\\LogManager->get('cloudwatch')
#3 D:\\Projects\\pagevamp\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\LogManager.php(581): Illuminate\\Log\\LogManager->driver()
#4 D:\\Projects\\pagevamp\\vendor\\pagevamp\\laravel-cloudwatch-logs\\src\\Providers\\CloudWatchServiceProvider.php(39): Illuminate\\Log\\LogManager->__call('listen', Array)
#5 [internal function]: Pagevamp\\Providers\\CloudWatchServiceProvider->boot()
. . . . 
```

Thanks for your help on this.

**Comment by developernaren** [comment] 2019-02-15 05:03
@johnboc 
As I mentioned in the doc

>This package relies on laravel's listener for log events. This package DOES NOT replace the default logging, instead adds additional log to AWS CLoud Watch. Hence you do not have to change the default log driver to make this work.

You DO NOT  have to change the LOG_CHANNEL. This will just work.

@gorankrgovic I will look into this tonight. Thank you for your patience.

**Comment by developernaren** [comment] 2019-02-15 05:51
@gorankrgovic I just tested this and is working fine for me in the queued jobs as well.

I would like to mention is that logs are sent in batch when the program terminates( end of laravel request cycle) to reduce the request to log server. So, if there are `die` and `dd` s in your code, this might not work and also this does not work in `tinker` because the program does not terminate there.



https://screenshots.firefox.com/tybqkM0OyZ7SB5n3/us-west-2.console.aws.amazon.com
this is my code in job

```
 public function handle()
    {
        \Log::info('this is working');
    }
```

**Comment by johnboc** [comment] 2019-02-15 08:26
Ok thanks for your help and patience. I have it working now.

**Comment by developernaren** [comment] 2019-02-23 17:04
Closing this issue as I cannot reproduce this and I am not getting any new context information regarding the issue.

**Closed by developernaren** 2019-02-23 17:04 UTC

**Comment by ninjasitm** [comment] 2019-08-20 19:28
@johnboc I'm experiencing this issue. What was your resolution?

**Comment by johnboc** [comment] 2019-08-21 09:14
Sorry but I'm not working on this project anymore and no longer have access to the project files.

**Comment by frankuriel** [comment] 2021-07-13 21:28
Please I have a problem. I followed all the steps but when I run the command to create a log I do not receive anything in cloudwatch
`Log::info('user logged in', ['id' => 123, 'name' => 'Preeti']);`

**Comment by mbarlund** [comment] 2021-09-14 16:11
Same problem. Other log channels work, but not cloudwatch. Cloudwatch works fine outside of a job handler.
